### ISSUE TITLE
Problems with dependency injection

### ISSUE THREAD

**Issue by odahcam** [imefisto/psr-swoole-native#1]
_Disclaimer: I believe this is not a bug in the lib, but an unexpected behavior by other libs that were not created to work in event-loop/async environments._

There's some issue with dependency injection where some values get replaced in the container on subsequent requests, because there's no thing in the container isolating each request's values.

I'm opening this here only to see if more people have the same issue and to try to find a solution to make this great library more viable.

Edit: I'd like to mention that I already openned an issue in the correct place: https://github.com/PHP-DI/PHP-DI/issues/762

**Comment by imefisto** [comment]
Thank you for giving a chance to the library. Please, could you provide some info about reproducing the issue? I could take a look later.

**Comment by odahcam** [comment]
Sorry I couldn't provide a good example, maybe in the future. Just to mention, this was one of the related issues I had: https://github.com/projek-xyz/slim-plates/issues/13
