### ISSUE TITLE
Slim4 with PHP8

### ISSUE THREAD

**Issue by IvAil0** [imefisto/psr-swoole-native#3]
/var/www # composer require "imefisto/psr-swoole-native"
Using version ^0.0.3 for imefisto/psr-swoole-native
./composer.json has been updated
Running composer update imefisto/psr-swoole-native
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dflydev/fig-cookies[v2.0.0, ..., v2.0.3] require php ^7.2 -> your php version (8.0.6) does not satisfy that requirement.
    - imefisto/psr-swoole-native v0.0.3 requires dflydev/fig-cookies ^2.0 -> satisfiable by dflydev/fig-cookies[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - Root composer.json requires imefisto/psr-swoole-native ^0.0.3 -> satisfiable by imefisto/psr-swoole-native[v0.0.3].

I checked dflydev/fig-cookies in version 3.0.0 already supports PHP8

**Comment by imefisto** [comment]
Thank you for pointing this out. I'll fix ASAP.

**Comment by imefisto** [comment]
This should be fixed, now. Thanks for your help!
