### ISSUE TITLE
composer.json: nyholm/psr7 should be in require rather than require-dev

### ISSUE THREAD

**Issue by cracksalad** [imefisto/psr-swoole-native#7]
Since the source code uses nyholm/psr7 it is not only necessary for development but also in production, right?

**Comment by imefisto** [comment]
Hi! The nyholm/psr7 is only used for tests and examples.

**Comment by cracksalad** [comment]
Oh sorry, I was looking at the examples and saw the `use`-statement thinking I was looking at the source code.
